In [1]:
import pandas as pd

In [ ]:
pip install pdfplumber

#Solar
```
 Conexão e acesso	REN 1.000 + a CP 033/2026, aberta agora
 Geração distribuída
```
#Eólica
	Cortes de geração	a norma de 2026 mais relevante (Portaria MME 140)
	Eólica offshore	lei nova + regulamentação de 2026

#Armazenamento	Autorização	REN 1.161/2026
	Conexão e faturamento

#1 ) WEB SCRAPER que irá pegar os dados diariamente do diário oficial da união:

In [ ]:
"""
Energy Start — Coletor diário do DOU (sem ZIP, sem INLABS)

Usa a página pública de leitura do jornal da Imprensa Nacional:
    https://www.in.gov.br/leiturajornal?data=DD-MM-AAAA&secao=do1
Ela traz, dentro do HTML, uma lista em JSON com todas as publicações do dia.
Cada publicação completa fica em:
    https://www.in.gov.br/web/dou/-/<urlTitle>

ATENÇÃO: não é uma API documentada. Se o site mudar, rode inspecionar_dia()
e ajuste os nomes dos campos.

Instalar:  pip install requests pandas
Uso no Colab:
    df = coletar_dia("21-09-2026")                    # um dia
    df = coletar_periodo("01-09-2026", "21-09-2026")  # vários dias
    df = classificar_df(df)                           # e segue para o classificador
"""

import html
import json
import re
import time
from datetime import datetime, timedelta

import pandas as pd
import requests

BASE = "https://www.in.gov.br"
CABECALHO = {"User-Agent": "Mozilla/5.0 (EnergyStart - hackathon COPPE)"}

# Quem entra e quem sai (aprendido no CSV de agosto: ANP e ANM passavam pelo filtro do MME)
ORGAOS_INCLUIR = ["Agência Nacional de Energia Elétrica", "Ministério de Minas e Energia",
                  "Conselho Nacional de Política Energética"]
ORGAOS_EXCLUIR = ["Agência Nacional do Petróleo", "Agência Nacional de Mineração"]


# ---------------------------------------------------------------------------
# 1. Lista de publicações do dia
# ---------------------------------------------------------------------------

def _json_da_pagina(pagina_html: str) -> list:
    m = re.search(r'<script[^>]*id="params"[^>]*>(.*?)</script>', pagina_html, flags=re.S)
    if not m:
        return []
    return json.loads(m.group(1)).get("jsonArray", [])


def listar_dia(data: str, secao: str = "do1") -> list:
    """data no formato DD-MM-AAAA. Devolve a lista bruta de publicações."""
    r = requests.get(f"{BASE}/leiturajornal", params={"data": data, "secao": secao},
                     headers=CABECALHO, timeout=60)
    r.raise_for_status()
    return _json_da_pagina(r.text)


def _interessa(item: dict) -> bool:
    orgao = item.get("hierarchyStr", "") or ""
    return (any(o in orgao for o in ORGAOS_INCLUIR)
            and not any(o in orgao for o in ORGAOS_EXCLUIR))


# ---------------------------------------------------------------------------
# 2. Texto completo de cada publicação
# ---------------------------------------------------------------------------

def _limpar(t: str) -> str:
    t = re.sub(r"<(script|style)[^>]*>.*?</\1>", " ", t, flags=re.S | re.I)
    t = re.sub(r"</p>|<br\s*/?>", "\n", t, flags=re.I)
    t = re.sub(r"<[^>]+>", " ", t)
    t = html.unescape(t)
    t = re.sub(r"[ \t\xa0]+", " ", t)
    return re.sub(r"\s*\n\s*", "\n", t).strip()


def baixar_texto(url_title: str) -> str:
    r = requests.get(f"{BASE}/web/dou/-/{url_title}", headers=CABECALHO, timeout=60)
    r.raise_for_status()
    # o corpo da matéria fica na div "texto-dou"; se não achar, usa a página inteira
    m = re.search(r'<div[^>]*class="[^"]*texto-dou[^"]*"[^>]*>(.*?)</div>\s*</div>',
                  r.text, flags=re.S)
    return _limpar(m.group(1) if m else r.text)


# ---------------------------------------------------------------------------
# 3. Coleta de um dia ou de um período
# ---------------------------------------------------------------------------

def coletar_dia(data: str, pausa: float = 1.5) -> pd.DataFrame:
    itens = [i for i in listar_dia(data) if _interessa(i)]
    linhas = []
    for item in itens:
        try:
            texto = baixar_texto(item["urlTitle"])
        except Exception as e:
            print(f"  [erro ao baixar] {item.get('title')}: {e}")
            continue
        linhas.append({
            "data": item.get("pubDate", data),
            "orgao": item.get("hierarchyStr", ""),
            "tipo": item.get("artType", ""),
            "titulo": item.get("title", "") or item.get("titulo", ""),
            "texto": texto,
            "link": f"{BASE}/web/dou/-/{item['urlTitle']}",
        })
        time.sleep(pausa)  # educação com o servidor do governo
    print(f"{data}: {len(itens)} publicações de ANEEL/MME/CNPE")
    return pd.DataFrame(linhas)


def coletar_periodo(inicio: str, fim: str) -> pd.DataFrame:
    d = datetime.strptime(inicio, "%d-%m-%Y")
    ultimo = datetime.strptime(fim, "%d-%m-%Y")
    partes = []
    while d <= ultimo:
        if d.weekday() < 5:  # o DOU ordinário sai de segunda a sexta
            try:
                partes.append(coletar_dia(d.strftime("%d-%m-%Y")))
            except Exception as e:
                print(f"{d:%d-%m-%Y}: falhou ({e})")
        d += timedelta(days=1)
    partes = [p for p in partes if len(p)]
    return pd.concat(partes, ignore_index=True) if partes else pd.DataFrame()


# ---------------------------------------------------------------------------
# 4. Diagnóstico, se algo parar de funcionar
# ---------------------------------------------------------------------------

def inspecionar_dia(data: str):
    itens = listar_dia(data)
    print(f"{len(itens)} publicações no dia. Campos do primeiro item:")
    if itens:
        print(json.dumps(itens[0], ensure_ascii=False, indent=2)[:1500])

#1.1) Teste com Dados Diretos do dou:

In [123]:
df = pd.read_csv("dou_agosto.csv")

In [124]:
df.head()

,data,orgao,tipo,titulo,texto,link
0,03/08/2026,Ministério de Minas e Energia/Agência Nacional...,Despacho,DESPACHO,DESPACHO\nFase de Requerimento de Pesquisa\nIn...,http://pesquisa.in.gov.br/imprensa/jsp/visuali...
1,03/08/2026,Ministério de Minas e Energia/Agência Nacional...,Despacho,"DESPACHO SDL-ANP Nº 1.160, DE 31 DE JULHO DE 2026","DESPACHO SDL-ANP Nº 1.160, DE 31 DE JULHO DE 2...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...
2,03/08/2026,Ministério de Minas e Energia/Agência Nacional...,Despacho,"DESPACHO SDL-ANP Nº 1.161, DE 31 DE JULHO DE 2026","DESPACHO SDL-ANP Nº 1.161, DE 31 DE JULHO DE 2...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...
3,03/08/2026,Ministério de Minas e Energia/Agência Nacional...,Despacho,"DESPACHO SDL-ANP Nº 1.162, DE 31 DE JULHO DE 2026","DESPACHO SDL-ANP Nº 1.162, DE 31 DE JULHO DE 2...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...
4,03/08/2026,Ministério de Minas e Energia/Secretaria Nacio...,Portaria,"PORTARIA SNTEP/MME Nº 3.168, DE 30 DE JULHO DE...","PORTARIA SNTEP/MME Nº 3.168, DE 30 DE JULHO DE...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...

In [125]:
df.iloc[-1]

data                                             31/08/2026
orgao     Ministério de Minas e Energia/Agência Nacional...
tipo                                               Despacho
titulo                                             Despacho
texto     Despacho\nRelação nº 190/2026\nFase de Autoriz...
link      http://pesquisa.in.gov.br/imprensa/jsp/visuali...
Name: 1569, dtype: object

In [127]:
df["titulo"] = df["titulo"].fillna("")
df["primeira_palavra"] = df["titulo"].str.split().str[0].str.upper()
df["primeira_palavra"].value_counts()

primeira_palavra
DESPACHO        1207
ALVARÁ           216
AUTORIZAÇÃO       51
RESOLUÇÃO         49
RETIFICAÇÃO       29
PORTARIA          13
SÚMULA             1
RETIFICAÇÕES       1
Name: count, dtype: int64

In [128]:
df_reso = df[df["primeira_palavra"]=="RESOLUÇÃO"]
df_reso.reset_index(drop=True, inplace=True)
df_reso

,data,orgao,tipo,titulo,texto,link,primeira_palavra
0,03/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.721, DE 28 DE JUL...","RESOLUÇÃO AUTORIZATIVA Nº 16.721, DE 28 DE JUL...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
1,03/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.723, DE 28 DE JUL...","RESOLUÇÃO AUTORIZATIVA Nº 16.723, DE 28 DE JUL...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
2,03/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.724, DE 28 DE JUL...","RESOLUÇÃO AUTORIZATIVA Nº 16.724, DE 28 DE JUL...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
3,03/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.725, DE 28 DE JUL...","RESOLUÇÃO AUTORIZATIVA Nº 16.725, DE 28 DE JUL...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
4,03/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.726, DE 28 DE JUL...","RESOLUÇÃO AUTORIZATIVA Nº 16.726, DE 28 DE JUL...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
5,04/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"Resolução ANM Nº 245, DE 31 DE julho DE 2026","Resolução ANM Nº 245, DE 31 DE julho DE 2026\n...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
6,04/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.728, DE 28 DE JUL...","RESOLUÇÃO AUTORIZATIVA Nº 16.728, DE 28 DE JUL...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
7,04/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.729, DE 28 DE JUL...","RESOLUÇÃO AUTORIZATIVA Nº 16.729, DE 28 DE JUL...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
8,04/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.730, DE 28 DE JUL...","RESOLUÇÃO AUTORIZATIVA Nº 16.730, DE 28 DE JUL...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
9,07/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"Resolução ANM Nº 246, DE 6 DE agosto DE 2026","Resolução ANM Nº 246, DE 6 DE agosto DE 2026\n...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
10,10/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.732, DE 4 DE AGOS...","RESOLUÇÃO AUTORIZATIVA Nº 16.732, DE 4 DE AGOS...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
11,10/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.733, DE 4 DE AGOS...","RESOLUÇÃO AUTORIZATIVA Nº 16.733, DE 4 DE AGOS...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
12,10/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.734, DE 4 DE AGOS...","RESOLUÇÃO AUTORIZATIVA Nº 16.734, DE 4 DE AGOS...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
13,10/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.735, DE 4 DE AGOS...","RESOLUÇÃO AUTORIZATIVA Nº 16.735, DE 4 DE AGOS...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
14,10/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.736, DE 4 DE AGOS...","RESOLUÇÃO AUTORIZATIVA Nº 16.736, DE 4 DE AGOS...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
15,12/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO ANP Nº 1.006, DE 11 DE AGOSTO DE 2026","RESOLUÇÃO ANP Nº 1.006, DE 11 DE AGOSTO DE 202...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
16,14/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.716, DE 21 DE JUL...","RESOLUÇÃO AUTORIZATIVA Nº 16.716, DE 21 DE JUL...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
17,14/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.737, DE 11 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.737, DE 11 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
18,14/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.741, DE 11 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.741, DE 11 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
19,14/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.742, DE 11 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.742, DE 11 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
20,14/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO HOMOLOGATÓRIA Nº 3.601, DE 11 DE AGO...","RESOLUÇÃO HOMOLOGATÓRIA Nº 3.601, DE 11 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
21,17/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.738, DE 11 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.738, DE 11 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
22,17/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.739, DE 11 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.739, DE 11 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
23,17/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.740, DE 11 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.740, DE 11 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
24,17/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.743, DE 11 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.743, DE 11 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
25,17/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.744, DE 11 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.744, DE 11 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
26,17/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.745, DE 11 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.745, DE 11 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
27,21/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.749, DE 18 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.749, DE 18 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
28,21/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.750, DE 18 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.750, DE 18 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
29,21/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO HOMOLOGATÓRIA Nº 3.602, DE 18 DE AGO...","RESOLUÇÃO HOMOLOGATÓRIA Nº 3.602, DE 18 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
30,25/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.746, DE 18 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.746, DE 18 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
31,25/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.748, DE 18 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.748, DE 18 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
32,25/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.751, DE 18 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.751, DE 18 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
33,25/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.752, DE 18 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.752, DE 18 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
34,25/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.753, DE 18 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.753, DE 18 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
35,26/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.747, DE 18 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.747, DE 18 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
36,26/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.761, DE 24 de ago...","RESOLUÇÃO AUTORIZATIVA Nº 16.761, DE 24 de ago...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
37,26/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO HOMOLOGATÓRIA Nº 3.604, DE 24 DE AGO...","RESOLUÇÃO HOMOLOGATÓRIA Nº 3.604, DE 24 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
38,26/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO HOMOLOGATÓRIA Nº 3.605, DE 24 DE AGO...","RESOLUÇÃO HOMOLOGATÓRIA Nº 3.605, DE 24 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
39,26/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO HOMOLOGATÓRIA Nº 3.606, DE 24 DE AGO...","RESOLUÇÃO HOMOLOGATÓRIA Nº 3.606, DE 24 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
40,27/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.754, DE 24 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.754, DE 24 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
41,28/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO ANP Nº 1.007, DE 27 DE AGOSTO DE 2026","RESOLUÇÃO ANP Nº 1.007, DE 27 DE AGOSTO DE 202...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
42,28/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.755, DE 24 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.755, DE 24 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
43,28/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.756, DE 24 de ago...","RESOLUÇÃO AUTORIZATIVA Nº 16.756, DE 24 de ago...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
44,28/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.757, DE 24 de ago...","RESOLUÇÃO AUTORIZATIVA Nº 16.757, DE 24 de ago...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
45,28/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.758, DE 24 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.758, DE 24 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
46,28/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.759, DE 24 DE AGO...","RESOLUÇÃO AUTORIZATIVA Nº 16.759, DE 24 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
47,28/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.760, DE 24 de ago...","RESOLUÇÃO AUTORIZATIVA Nº 16.760, DE 24 de ago...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO
48,28/08/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO HOMOLOGATÓRIA Nº 3.603, DE 24 DE AGO...","RESOLUÇÃO HOMOLOGATÓRIA Nº 3.603, DE 24 DE AGO...",http://pesquisa.in.gov.br/imprensa/jsp/visuali...,RESOLUÇÃO

# O que importa

1. Resolução (49): a mais importante. É onde as regras mudam. Dentro dela há três tipos, e todos servem para vocês:

Normativa (REN): cria ou altera regras gerais, como as de geração distribuída e conexão. É o coração do produto.
Homologatória (REH): reajuste de tarifa das distribuidoras, que muda o valor da compensação solar.
Autorizativa (REA): autoriza usinas específicas, o que conversa com a subárea Outorga eólica.

2. Portaria (13): média. Algumas do MME definem diretrizes importantes; outras são administrativas. São poucas, então deixem passar e o classificador decide.

3. Despacho (1.207): pouca coisa útil no meio de muito volume. A maioria trata de casos individuais: registrar uma usina, aprovar um documento, decidir um processo. Alguns interessam (registro de usina eólica ou solar, decisões sobre cortes de geração), mas a maior parte não. Aqui vale um filtro de palavras-chave antes do LLM, para não gastar classificação com mil despachos irrelevantes.

4. Retificação (30): baixa, mas não descartem. Corrige um ato anterior. Se corrigir uma resolução normativa, importa.

In [129]:
df["subtipo"] = df["titulo"].str.upper().str.extract(r"RESOLUÇÃO\s+(\w+)")
df["subtipo"].value_counts()

df_teste = df[df["subtipo"].isin(["NORMATIVA", "HOMOLOGATÓRIA"])]
len(df_teste)

6

In [130]:
for n in range(len(df_teste)):

  print(df_teste["texto"].iloc[n])

RESOLUÇÃO HOMOLOGATÓRIA Nº 3.601, DE 11 DE AGOSTO DE 2026
O DIRETOR-GERAL DA AGÊNCIA NACIONAL DE ENERGIA ELÉTRICA - ANEEL, com base no art. 16, IV, do Regimento Interno da ANEEL, resolve:
Processo nº: 48500.016427/2026-62. Interessados: Companhia de Eletricidade do Amapá - Equatorial CEA (CNPJ nº 05.965.546/0001-09), Câmara de Comercialização de Energia Elétrica - CCEE, UHE Coaracy Nunes, Linhas de Macapá Transmissora de Energia S.A. - LMTE, Energisa Amapá Transmissora de Energia S.A. - EAP, concessionárias e permissionárias de distribuição, consumidores, usuários e agentes do Setor. Objeto: Prorrogar a vigência das tarifas da Companhia de Eletricidade do Amapá - Equatorial CEA, previstas na Resolução Homologatória nº 3.572, de 7 de abril de 2026, pelo período de 13 de dezembro de 2026 a 24 de maio de 2027. A íntegra desta Resolução e de seus anexos estão juntados aos autos e disponíveis no endereço eletrônico legislacao.aneel.gov.br.
SANDOVAL DE ARAÚJO FEITOSA NETO
RESOLUÇÃO HOMOLOGATÓRIA Nº 3.602, DE 18 DE AGOSTO DE 2026
O DIRETOR-GERAL DA AGÊNCIA NACIONAL DE ENERGIA ELÉTRICA - ANEEL, com base no art. 16, IV, do Regimento Interno da ANEEL, resolve:
Processo nº 48500.030135/2025-51. Interessados: Celesc Distribuição S.A. - Celesc-DIS (CNPJ nº 08.336.783/0001-90), Câmara de Comercialização de Energia Elétrica - CCEE, Neoenergia Vale do Itajaí Transmissão de Energia S.A. - Vale do Itajaí, AXIA Energia Sul S.A.- AXIA Sul, Sistema de Transmissão Catarinense S.A - STC, Empresa de Transmissão Serrana S.A. - ETSE, EVOLTZ VI - Campos Novos Transmissora de Energia S.A. - ATE VI, Interligação Elétrica Biguaçu S.A - IE Biguaçu, Interligação Elétrica Sul S.A. - IESUL e Transmissão Litoral Sul S.A. - LITORAL SUL, concessionárias e permissionárias de distribuição, consumidores, usuários e agentes do Setor. Objeto: Homologa o resultado da Revisão Tarifária Periódica de 2026 da Celesc Distribuição S.A. - Celesc-DIS, a vigorar a partir de 22 de agosto de 2026, e dá outras providências. A íntegra desta Resolução e de seus anexos estão juntados aos autos e disponíveis no endereço eletrônico Legislacao.aneel.gov.br
SANDOVAL DE ARAÚJO FEITOSA NETO
RESOLUÇÃO HOMOLOGATÓRIA Nº 3.604, DE 24 DE AGOSTO DE 2026
O DIRETOR-GERAL DA AGÊNCIA NACIONAL DE ENERGIA ELÉTRICA - ANEEL, com base no art. 16, IV, do Regimento Interno da ANEEL, resolve:
Processo nº 48500.030944/2025-63. Interessados: Equatorial Maranhão Distribuidora de Energia S.A. - Equatorial MA (CNPJ nº 06.272.793/0001-84), Câmara de Comercialização de Energia Elétrica - CCEE, Tangará Transmissora De Energia Elétrica S/A - Tangará Transmissora, AXIA Energia Norte S.A. - AXIA Norte, AXIA Energia Nordeste S.A. - AXIA Nordeste, Encruzo Novo Transmissora de Energia Ltda. - Encruzo, Arteon Z2 Energia S.A. - Arteon Z2, Horizon Transmissão MA I S.A. - MA I e Horizon Transmissão MA II S.A. - MA II, concessionárias e permissionárias de distribuição, consumidores, usuários e agentes do Setor. Objeto: Homologa o resultado do Reajuste Tarifário Anual de 2026 da Equatorial Maranhão Distribuidora de Energia S.A. - Equatorial MA, a vigorar a partir de 28 de agosto de 2026, e dá outras providências. A íntegra desta Resolução e de seus anexos estão juntados aos autos e disponíveis no endereço eletrônico legislacao.aneel.gov.br.
SANDOVAL DE ARAÚJO FEITOSA NETO
RESOLUÇÃO HOMOLOGATÓRIA Nº 3.605, DE 24 DE AGOSTO DE 2026
O DIRETOR-GERAL DA AGÊNCIA NACIONAL DE ENERGIA ELÉTRICA - ANEEL, com base no art. 16, IV, do Regimento Interno da ANEEL, resolve:
Processo nº 48500.030942/2025-74. Interessados: Elektro Eletricidade e Serviços S/A - Neoenergia Elektro (CNPJ nº 02.328.280/0001-97), Câmara de Comercialização de Energia Elétrica - CCEE, Marechal Rondon Transmissora de Energia S.A. - Rondon, Interligação Elétrica Jaguar 9 S.A. - IE Jaguar 9 e ISA Energia Brasil S.A. - ISA Energia Brasil, concessionárias e permissionárias de distribuição, consumidores, usuários e agentes do Setor. Objeto: Homologa o resultado do Reajuste Tarifário Anual de 2026 da Elektro Eletricidade e Serviços S/A - Neoenergia Elektro, a vigorar a partir de 27 de agosto de 2026, e dá outras providências. A íntegra desta Resolução e de seus anexos estão juntados aos autos e disponíveis no endereço eletrônico legislacao.aneel.gov.br.
SANDOVAL DE ARAÚJO FEITOSA NETO
RESOLUÇÃO HOMOLOGATÓRIA Nº 3.606, DE 24 DE AGOSTO DE 2026
O DIRETOR-GERAL DA ANEEL, com base no art. 16, IV, do Regimento Interno da ANEEL, resolve:
Processo nº 48500.030137/2025-41. Interessados: Força e Luz Coronel Vivida Ltda - Pacto Energia (CNPJ nº 79.850.574/0001-09), Câmara de Comercialização de Energia Elétrica - CCEE, concessionárias e permissionárias de distribuição, consumidores, usuários e agentes do Setor. Objeto: Homologar o resultado provisório da Revisão Tarifária Periódica - RTP de 2026 da Força e Luz Coronel Vivida Ltda - Pacto Energia, a vigorar a partir de 26 de agosto de 2026, e dá outras providências. A íntegra desta Resolução e de seus anexos estão juntados aos autos e disponíveis no endereço eletrônico legislacao.aneel.gov.br.
SANDOVAL DE ARAÚJO FEITOSA NETO
RESOLUÇÃO HOMOLOGATÓRIA Nº 3.603, DE 24 DE AGOSTO DE 2026
O DIRETOR-GERAL DA AGÊNCIA NACIONAL DE ENERGIA ELÉTRICA - ANEEL, com base no art. 16, IV, do Regimento Interno da ANEEL, resolve:
Processo nº 48500.030945/2025-16. Interessados: Energisa Paraíba - Distribuidora de Energia - Energisa PB (CNPJ nº 09.095.183/0001-40), Câmara de Comercialização de Energia Elétrica - CCEE, AXIA Energia Nordeste S.A. - AXIA Nordeste, Borborema Transmissão de Energia S. A. - Borborema, concessionárias e permissionárias de distribuição, consumidores, usuários e agentes do Setor. Objeto: Homologa o resultado do Reajuste Tarifário Anual de 2026 da Energisa Paraíba - Distribuidora de Energia - Energisa PB, a vigorar a partir de 28 de agosto de 2026, e dá outras providências. A íntegra desta Resolução e de seus anexos estão juntados aos autos e disponíveis no endereço eletrônico legislacao.aneel.gov.br.
SANDOVAL DE ARAÚJO FEITOSA NETO

#Como o texto em si da norma está no site da ENEEL, vou passar para pegar os dados na Lei.org que possui todas as esferas Federal , estadual e municipal

# 2 ) Aneel + Busca do claude

In [64]:
"""
Energy Start — Pré-processamento dos PDFs (Leis.org / ANEEL)

Lê todos os PDFs de uma pasta, limpa o texto e devolve um DataFrame
no mesmo formato que o classificar_df() espera (coluna "texto").

Limpezas feitas:
  1. remove o rodapé "Leis.org/aneel ... Gerado em ..." e a numeração "1/15";
  2. remove a redação ANTIGA quando o texto consolidado traz as duas
     versões ("... (Redação dada pela Resolução Normativa nº X)");
  3. remove dispositivos revogados;
  4. separa a lista "Atos que alteram... / Atos que são alterados..."
     do final, que é do site e não da norma.

Instalar:  pip install pdfplumber pandas
Uso:
    df = carregar_pdfs(r"C:\\caminho\\da\\pasta")
    novidades = df[df["uso"] == "novidade"]      # vão para o classificador
    estoque   = df[df["uso"] == "estoque"]       # vão para a base do copiloto
"""

import re
from pathlib import Path

import pandas as pd
import pdfplumber

LIMITE_ESTOQUE = 150_000  # acima disso (ex.: REN 1.000), é norma-base, não novidade

# Início de um dispositivo: "Art. 12.", "Art. 655-A", "§ 2º", "Parágrafo único",
# "XXIX-A -", "IV -", "a)"
ROTULO = re.compile(
    r"^\s*(Art\.\s*\d+[º°]?(?:-[A-Z]+)?|§\s*\d+[º°]?|Parágrafo único|"
    r"[IVXLC]+(?:-[A-Z]+)?\s+-|[a-z]\))"
)


# ---------------------------------------------------------------------------
# Leitura
# ---------------------------------------------------------------------------

def ler_pdf(caminho: Path) -> tuple[str, int]:
    """pdfplumber mantém o 'Art. 1º' no lugar certo (o pypdf solta o número do texto)."""
    with pdfplumber.open(caminho) as pdf:
        paginas = [p.extract_text() or "" for p in pdf.pages]
    return "\n".join(paginas), len(paginas)


# ---------------------------------------------------------------------------
# Limpeza
# ---------------------------------------------------------------------------

def remover_rodapes(texto: str) -> str:
    texto = re.sub(r"Leis\.org/aneel\s*-.*?Gerado em:\s*[\d/]+\s*[\d:]+", "", texto)
    texto = re.sub(r"^\s*\d+/\d+\s*$", "", texto, flags=re.M)
    return texto


def separar_atos_relacionados(texto: str) -> tuple[str, str]:
    m = re.search(r"Atos que alteram, regulamentam ou revogam", texto)
    if not m:
        return texto, ""
    return texto[: m.start()].strip(), texto[m.start():].strip()


def _chave(rotulo: str) -> str:
    """'Art. 176' e 'Art. 176.' viram a mesma chave."""
    return re.sub(r"[\s.º°]", "", rotulo).lower()


def remover_redacoes_antigas(texto: str) -> str:
    # 1) junta as linhas quebradas em dispositivos inteiros
    blocos: list[str] = []
    for linha in texto.splitlines():
        if not linha.strip():
            continue
        if ROTULO.match(linha) or not blocos:
            blocos.append(linha.strip())
        else:
            blocos[-1] += " " + linha.strip()

    # 2) quando aparece a redação nova, apaga a antiga com o mesmo rótulo
    manter = [True] * len(blocos)
    for i, bloco in enumerate(blocos):
        novo = "(Redação dada pela" in bloco
        revogado = "(Revogado pel" in bloco or "(Revogada pel" in bloco
        if revogado:
            manter[i] = False
        if not (novo or revogado):
            continue
        m = ROTULO.match(bloco)
        if not m:
            continue
        chave = _chave(m.group(1))
        for j in range(i - 1, max(i - 15, -1), -1):  # procura a versão antiga logo antes
            mj = ROTULO.match(blocos[j])
            if mj and _chave(mj.group(1)) == chave and manter[j]:
                manter[j] = False
                break

    return "\n".join(b for b, ok in zip(blocos, manter) if ok)


def extrair_titulo(texto: str) -> str:
    m = re.search(r"RESOLUÇÃO NORMATIVA[^\n]*?Nº\s*[\d.]+,?\s*DE\s+[^\n(]+?\d{4}", texto, flags=re.I)
    return m.group(0).strip() if m else ""


def extrair_data_dou(texto: str) -> str:
    """Leis.org informa: 'Este texto não substitui o publicado no D.O. de 08.04.2025'."""
    m = re.search(r"publicado no D\.?O\.?\s*de\s*(\d{2}\.\d{2}\.\d{4})", texto)
    return m.group(1).replace(".", "/") if m else ""


# ---------------------------------------------------------------------------
# Função principal
# ---------------------------------------------------------------------------

def carregar_pdfs(pasta: str) -> pd.DataFrame:
    linhas = []
    for caminho in sorted(Path(pasta).glob("*.pdf")):
        bruto, n_paginas = ler_pdf(caminho)
        if not bruto.strip():
            print(f"[sem texto] {caminho.name} — PDF escaneado?")
            continue

        texto = remover_rodapes(bruto)
        titulo = extrair_titulo(texto)  # antes de juntar as linhas, senão pega a ementa junto
        if not titulo:
            print(f"[ignorado] {caminho.name} — não parece uma norma")
            continue
        texto, atos = separar_atos_relacionados(texto)
        texto = remover_redacoes_antigas(texto)

        linhas.append({
            "arquivo": caminho.name,
            "titulo": titulo,
            "data": extrair_data_dou(texto),
            "paginas": n_paginas,
            "caracteres": len(texto),
            "uso": "estoque" if len(texto) > LIMITE_ESTOQUE else "novidade",
            "texto": texto,
            "atos_relacionados": atos,
        })

    df = pd.DataFrame(linhas)
    print(df[["arquivo", "paginas", "caracteres", "uso"]].to_string(index=False))
    return df


if __name__ == "__main__":
    import sys
    pasta = "Normas"
    carregar_pdfs(pasta).to_csv("normas_pdf.csv", index=False, encoding="utf-8-sig")

[ignorado] lei-14300-6-janeiro-2022-792217-normaatualizada-pl.pdf — não parece uma norma
                                   arquivo  paginas  caracteres      uso
Resolucao-normativa-1115-2025-Aneel-BR.pdf        3        4463 novidade
Resolucao-normativa-1147-2025-Aneel-BR.pdf       15       25042 novidade
Resolucao-normativa-1148-2026-Aneel-BR.pdf       15       21851 novidade
Resolucao-normativa-1150-2026-Aneel-BR.pdf        4        5263 novidade
       aren2021956_prodist_modulo_3_v8.pdf       41        1528 novidade

In [65]:
df_normas=pd.read_csv("normas_pdf.csv")
df_normas

,arquivo,titulo,data,paginas,caracteres,uso,texto,atos_relacionados
0,Resolucao-normativa-1115-2025-Aneel-BR.pdf,"RESOLUÇÃO NORMATIVA ANEEL Nº 1.115, DE 1º DE A...",08/04/2025,3,4463,novidade,AGÊNCIA NACIONAL DE ENERGIA ELÉTRICA - ANEEL R...,"Atos que alteram, regulamentam ou revogam esta..."
1,Resolucao-normativa-1147-2025-Aneel-BR.pdf,"RESOLUÇÃO NORMATIVA Nº 1.147, DE 9 DE DEZEMBRO...",16/12/2025,15,25042,novidade,AGÊNCIA NACIONAL DE ENERGIA ELÉTRICA - ANEEL R...,"Atos que alteram, regulamentam ou revogam esta..."
2,Resolucao-normativa-1148-2026-Aneel-BR.pdf,"RESOLUÇÃO NORMATIVA ANEEL Nº 1.148, DE 27 DE J...",20/02/2026,15,21851,novidade,AGÊNCIA NACIONAL DE ENERGIA ELÉTRICA - ANEEL R...,"Atos que alteram, regulamentam ou revogam esta..."
3,Resolucao-normativa-1150-2026-Aneel-BR.pdf,"RESOLUÇÃO NORMATIVA ANEEL Nº 1.150, DE 27 DE J...",02/02/2026,4,5263,novidade,AGÊNCIA NACIONAL DE ENERGIA ELÉTRICA - ANEEL R...,"Atos que alteram, regulamentam ou revogam esta..."
4,aren2021956_prodist_modulo_3_v8.pdf,"RESOLUÇÃO NORMATIVA ANEEL Nº 956, DE 7 DE DEZE...",NaN,41,1528,novidade,"ANEXO III DA RESOLUÇÃO NORMATIVA ANEEL Nº 956,...",NaN

In [11]:
df_normas["texto"][0]

'AGÊNCIA NACIONAL DE ENERGIA ELÉTRICA - ANEEL RESOLUÇÃO NORMATIVA ANEEL Nº 1.000, DE 7 DE DEZEMBRO DE 2021(*) (Vide Despacho nº 1.731/2025 - Aplicação da Tarifa Social de Energia Elétrica, alterada pela Medida Provisória nº1 .300/2025, nos termos dos arts. 179, §§ 1º e 2º, e art. 291, inciso III) Despacho 2.006/2024: Decisão Judicial - suspensos os efeitos referentes ao prazo de 60 (sessenta) ciclos estabelecidos no inciso II do art. 323. Estabelece as Regras de Prestação do Serviço Público de Distribuição de Energia Elétrica; revoga as Resoluções Normativas ANEEL nº 414, de 9 de setembro de 2010; nº 470, de 13 de dezembro de 2011; nº 901, de 8 de dezembro de 2020 e dá outras providências. O DIRETOR-GERAL DA AGÊNCIA NACIONAL DE ENERGIA ELÉTRICA - ANEEL, no uso de suas atribuições regimentais, de acordo com a deliberação da Diretoria, tendo em vista o disposto na Lei nº 9.427, de 26 de dezembro de 1996, no Decreto nº 2.335, de 6 de outubro de 1997 e o que consta do Processo nº 48500.005218/2020-06, resolve : TÍTULO I PARTE GERAL CAPÍTULO I DAS DISPOSIÇÕES GERAIS Seção I Do Objeto e âmbito de Aplicação\nArt. 1º Esta Resolução Normativa estabelece as Regras de Prestação do Serviço Público de Distribuição de Energia Elétrica, nas quais estão dispostos os direitos e deveres do consumidor e demais usuários do serviço.\n§ 1º O disposto nesta Resolução aplica-se à concessionária e permissionária de serviço público de distribuição de energia elétrica e ao usuário do serviço, pessoa física ou jurídica que se beneficia ou utiliza, efetiva ou potencialmente, do serviço público, a exemplo de:\nI - consumidor;\nII - central geradora;\nIII - distribuidora;\nIV - agente exportador; (Redação dada pela Resolução Normativa nº 1162/2026)\nV - agente importador; e (Redação dada pela Resolução Normativa nº 1162/2026)\nVI - armazenador autônomo. (Redação acrescida pela Resolução Normativa nº1 162/2026)\n§ 2º A aplicação desta Resolução é complementada pelos Procedimentos de Distribuição de Energia Elétrica no Sistema Elétrico Nacional - PRODIST e pelos Procedimentos de Regulação Tarifária - PRORET.\n§ 3º A aplicação desta Resolução não afasta a necessidade de cumprimento do disposto na regulação da ANEEL e na legislação, em especial:\nI - na Lei nº 8.078, de 11 de setembro de 1990, que instituiu o Código de Defesa do Consumidor e estabelece normas de proteção e defesa do consumidor, de ordem pública e interesse social; e\nII - na Lei nº 13.460, de 26 de junho de 2017, que dispõe sobre a participação, proteção e defesa dos direitos do usuário dos serviços públicos.\n§ 4º Aplica-se o disposto nesta Resolução, de forma subsidiária e complementar, ao consumidor e demais usuários que acessam o sistema de distribuição por meio de conexão às Demais Instalações de Transmissão - DIT, ou que possuam contratos celebrados com a distribuidora. Seção II Das Definições\nArt. 2º Para os fins e efeitos desta Resolução, são adotadas as seguintes definições:\nI - área urbana: parcela do território, contínua ou não, incluída no perímetro urbano pelo Plano Diretor ou por lei municipal específica;\nI-A - autoconsumo remoto: modalidade de participação no SCEE caracterizada por:\na) unidades consumidoras de titularidade de uma mesma pessoa física ou jurídica, incluídas matriz e filial;\nb) possuir unidade consumidora com microgeração ou minigeração distribuída em local diferente das unidades consumidoras que recebem excedentes de energia; e\nc) atendimento de todas as unidades consumidoras pela mesma distribuidora. (Redação acrescida pela Resolução Normativa nº1 059/2023)\nI-B - autoconsumo local: modalidade de participação no SCEE caracterizada por:\na) titularidade de uma pessoa física ou jurídica;\nb) microgeração ou minigeração distribuída eletricamente junto à carga; e\nc) o excedente e o crédito de energia elétrica gerados por unidade consumidora são integralmente compensados pela mesma unidade consumidora. (Redação acrescida pela Resolução Normativa nº 1098/2024)\nI - C - armazenador autônomo: agente autorizado ou registrado titular de SAE Autônomo; (Redação acrescida pela Resolução Normativa nº 1162/2026)\nII - bandeiras tarifárias: sistema que tem como finalidade sinalizar os custos atuais da geração de energia elétrica ao consumidor por meio da tarifa de energia;\nIII - carga instalada: soma das potências nominais dos equipamentos elétricos instalados na unidade consumidora e em condições de entrar em funcionamento, expressa em kW (quilowatts);\nIV - central geradora: agente concessionário, autorizado ou registrado de geração de energia elétrica;\nIV-A - central geradora de fonte despachável: central geradora que pode ser despachada por meio de um controlador local ou remoto, com as seguintes características:\na) hidrelétrica de até 5 MW de potência instalada, incluídas aquelas a fio d`água que possuam viabilidade de controle variável de sua geração de energia;\nb) termelétrica de até 5 MW de potência instalada, classificadas como cogeração qualificada, ou movida à biomassa ou biogás; ou\nc) fotovoltaica de até 3 MW de potência instalada, que apresentem capacidade de modulação de geração por meio de armazenamento de energia em baterias, em quantidade de, pelo menos, 20% da capacidade de geração mensal das unidades de geração fotovoltaicas, nos termos do art. 655-B; (Redação acrescida pela Resolução Normativa nº 1059/2023)\nV - ciclo de faturamento: intervalo de tempo correspondente ao faturamento de determinada unidade consumidora;\nVI - concessionária: agente titular de concessão federal para prestar o serviço público de distribuição de energia elétrica, de agora em diante denominado distribuidora;\nVII - consumidor: pessoa física ou jurídica que solicite o fornecimento do serviço à distribuidora, assumindo as obrigações decorrentes desta prestação à sua unidade consumidora;\nVIII - consumidor especial: consumidor livre ou o conjunto de consumidores livres reunidos por comunhão de interesses de fato ou de direito, cuja carga seja maior ou igual a 500 kW e que tenha adquirido energia elétrica na forma estabelecida no § 5º do art. 26 da Lei nº 9.427, de 26 de dezembro de 1996;\nIX - consumidor livre: consumidor, atendido em qualquer tensão, que tenha exercido a opção de compra de energia elétrica, conforme as condições estabelecidas no art. 15 e no art.16 da Lei nº 9.074, de 7 de julho de 1995;\nX - consumidor potencialmente livre: consumidor que cumpre as condições estabelecidas para tornar-se livre, mas é atendido de forma regulada;\nX-A - crédito de energia: excedente de energia não utilizado no ciclo de faturamento em que foi injetado e que não tenha sido objeto de compra pela distribuidora na forma prevista no art. 24 da Lei nº 14.300/2022; (Redação acrescida pela Resolução Normativa nº 1059/2023)\nXI - demanda: média das potências elétricas ativas ou reativas, injetada ou requerida do sistema elétrico de distribuição durante um intervalo de tempo especificado;\nXII - demanda contratada: demanda de potência ativa a ser obrigatória e continuamente disponibilizada pela distribuidora no ponto de conexão, conforme valor e período de vigência fixados em contrato, em kW (quilowatts);\nXIII - demanda medida: maior demanda de potência ativa injetada ou requerida do sistema elétrico de distribuição pela carga ou geração, verificada por medição e integralizada em intervalos de 15 minutos durante o período de faturamento, em kW (quilowatts);\nXIV - distribuidora: agente titular de concessão ou permissão federal para prestar o serviço público de distribuição de energia elétrica;\nXIV-A - empreendimento com múltiplas unidades consumidoras com microgeração ou minigeração distribuída: conjunto de unidades consumidoras caracterizado por:\na) localização das unidades consumidoras em uma mesma propriedade ou em propriedades contíguas, sem separação por vias públicas, passagem aérea ou subterrânea, ou por propriedades de terceiros não integrantes do empreendimento;\nb) conexão da microgeração ou minigeração distribuída na unidade consumidora de atendimento das áreas comuns, distinta das demais, com a utilização da energia elétrica de forma independente; e\nc) responsabilidade do condomínio, da administração ou do proprietário do empreendimento pela unidade consumidora em que se conecta a microgeração ou minigeração distribuída; (Redação acrescida pela Resolução Normativa nº 1059/2023)\nXV - estação de recarga: conjunto de softwares e equipamentos utilizados para o fornecimento de corrente alternada ou contínua ao veículo elétrico, instalado em um ou mais invólucros, com funções especiais de controle e de comunicação, e localizados fora do veículo;\nXVI - energia elétrica ativa: aquela que pode ser convertida em outra forma de energia, em kWh (quilowatts-hora);\nXVI-A - energia compensada: energia elétrica ativa consumida da rede e compensada pela energia elétrica ativa injetada, pelo excedente de energia e pelo crédito de energia utilizados no faturamento de unidade consumidora participante do Sistema de Compensação de Energia Elétrica, limitada ao montante de energia consumida da rede no ciclo de faturamento; (Redação acrescida pela Resolução Normativa nº 1059/2023)\nXVII - energia elétrica reativa: aquela que circula entre os diversos campos elétricos e magnéticos de um sistema de corrente alternada sem produzir trabalho, em kvarh (quilovolt-ampère-reativo-hora);\nXVII-A - excedente de energia: diferença positiva entre a energia elétrica ativa injetada e a energia elétrica ativa consumida por unidade consumidora com microgeração ou minigeração distribuída, apurada por posto tarifário a cada ciclo de faturamento, exceto para o caso de empreendimento com múltiplas unidades consumidoras com microgeração ou minigeração distribuída ou geração compartilhada, em que o excedente de energia pode ser toda a energia gerada ou a injetada na rede de distribuição pela unidade consumidora, a critério do titular da unidade consumidora com microgeração ou minigeração distribuída; (Redação acrescida pela Resolução Normativa nº 1059/2023)\nXVIII - exportador: agente titular de autorização federal para exportar energia elétrica;\nXIX - fator de carga: razão entre a demanda média e a demanda máxima da unidade consumidora, ocorridas no mesmo intervalo de tempo;\nXX - fator de demanda: razão entre a demanda máxima num intervalo de tempo e a carga instalada na unidade consumidora;\nXXI - fator de potência: razão entre a energia elétrica ativa e a raiz quadrada da soma dos quadrados das energias elétricas ativa e reativa, consumidas num mesmo período;\nXXII - fatura: documento emitido pela distribuidora com a quantia monetária total a ser paga pelo consumidor e demais usuários pela prestação do serviço público de distribuição de energia elétrica e por outros serviços e atividades, função que pode ser cumprida pelo documento fiscal denominado "Nota Fiscal/Conta de Energia Elétrica";\nXXII-A - geração compartilhada: modalidade de participação no SCEE caracterizada pela reunião de consumidores, por meio de consórcio, cooperativa, condomínio civil voluntário ou edilício, ou qualquer outra forma de associação civil instituída para esse fim, composta por pessoas físicas ou jurídicas que possuam unidade consumidora com microgeração ou minigeração distribuída; (Redação acrescida pela Resolução Normativa nº 1059/2023)\nXXIII - grupo A: grupamento composto de unidades consumidoras com conexão em tensão maior ou igual a 2,3 kV, ou atendidas a partir de sistema subterrâneo de distribuição em tensão menor que 2,3 kV, e subdividido nos seguintes subgrupos:\na) subgrupo A1: tensão de conexão maior ou igual a 230 kV;\nb) subgrupo A2: tensão de conexão maior ou igual a 88 kV e menor ou igual a 138 kV;\nc) subgrupo A3: tensão de conexão igual a 69 kV;\nd) subgrupo A3a: tensão de conexão maior ou igual a 30 kV e menor ou igual a 44 kV;\ne) subgrupo A4: tensão de conexão maior ou igual a 2,3 kV e menor ou igual a 25 kV; e\nf) subgrupo AS: tensão de conexão menor que 2,3 kV, a partir de sistema subterrâneo de distribuição;\nXXIV - grupo B: grupamento composto de unidades consumidoras com conexão em tensão menor que 2,3 kV e subdividido nos seguintes subgrupos:\na) subgrupo B1: residencial;\nb) subgrupo B2: rural;\nc) subgrupo B3: demais classes; e\nd) subgrupo B4: Iluminação Pública;\nXXV - importador: agente titular de autorização federal para importar energia elétrica;\nXXVI - infraestrutura local: infraestrutura necessária à administração e operação da central geradora ou SAE autônomo, tais como sistemas e edificações diversos (almoxarifado, oficinas, iluminação externa etc.), não incluindo serviços auxiliares; (Redação dada pela Resolução Normativa nº 1162/2026)\nXXVII - inspeção: fiscalização posterior à conexão para verificar a adequação aos padrões técnicos e de segurança da distribuidora, o funcionamento do sistema de medição e a confirmação dos dados cadastrais;\nXXVIII - instalações de interesse restrito: instalações de armazenador autônomo, central geradora, exportador ou importador de energia, que tenham a finalidade de interligação até o ponto de conexão, podendo ser denominadas de instalações de uso exclusivo; (Redação dada pela Resolução Normativa nº 1162/2026)\nXXIX - medição: processo realizado por equipamento que possibilite a quantificação e o registro de grandezas elétricas associadas ao consumo ou injeção de energia elétrica e à potência ativa ou reativa, caso aplicável; (Redação dada pela Resolução Normativa nº 1162/2026)\nXXIX-A - microgeração distribuída: central geradora de energia elétrica que utilize fontes renováveis ou, conforme Resolução Normativa nº 1.031, de 26 de julho de 2022, de cogeração qualificada, conectada à rede de distribuição de energia elétrica por meio de unidade consumidora, da qual é considerada parte, que possua potência instalada em corrente alternada menor ou igual a 75 kW; (Redação acrescida pela Resolução Normativa nº 1059/2023)\nXXIX-B - minigeração distribuída: central geradora de energia elétrica que utilize fontes renováveis ou, conforme Resolução Normativa nº 1.031, de 26 de julho de 2022, de cogeração qualificada, conectada à rede de distribuição de energia elétrica por meio de unidade consumidora, da qual é considerada parte, que possua potência instalada em corrente alternada maior que 75 kW e menor ou igual a:\na) 5 MW para as centrais geradoras de fontes despacháveis;\nb) 3 MW para as demais fontes não enquadradas como centrais geradoras de fontes despacháveis; ou\nc) 5 MW para unidades consumidoras já conectadas em 7 de janeiro de 2022 ou que protocolarem solicitação de orçamento de conexão, nos termos da Seção IX do Capítulo II do Título I, até 7 de janeiro de 2023, independentemente do enquadramento como centrais geradoras de fontes despacháveis. (Redação acrescida pela Resolução Normativa nº 1059/2023)\nXXX - microssistema isolado de geração e distribuição de energia elétrica - MIGDI: sistema isolado de geração de energia elétrica com fonte de energia renovável intermitente, utilizado para o atendimento de mais de uma unidade consumidora e associado a microrrede de distribuição de energia elétrica;\nXXXI - modalidade tarifária: conjunto de tarifas aplicáveis às componentes de consumo de energia elétrica e demanda, conforme Capítulo VII do Título I;\nXXXII - módulo de infraestrutura geral: conjunto de equipamentos, materiais e serviços de infraestrutura comuns à subestação, tais como terreno, cercas, terraplenagem, drenagem, grama, embritamento, pavimentação, arruamento, iluminação do pátio, proteção contra incêndio, abastecimento de água, redes de esgoto, malha de terra e cabos para-raios, canaletas principais, edificações, serviço auxiliar, área industrial e caixa separadora de óleo;\nXXXIII - perícia metrológica: atividade desenvolvida pelo órgão metrológico, entidade por ele delegada ou terceiro legalmente habilitado, para examinar e certificar as condições físicas em que se encontra um determinado sistema ou equipamento de medição;\nXXXIV - permissionária: agente titular de permissão federal para prestar o serviço público de distribuição de energia elétrica, doravante denominado distribuidora;\nXXXV - ponto de conexão: conjunto de materiais e equipamentos que se destina a estabelecer a conexão entre as instalações da distribuidora e do consumidor e demais usuários;\nXXXVI - pós-pagamento eletrônico: modalidade de faturamento em que as informações da energia elétrica consumida são armazenadas e consolidadas em dispositivo eletrônico que viabilize o pagamento pelo consumidor;\nXXXVII - posto de transformação: compreende o transformador de distribuição e seus acessórios, tais como os dispositivos de manobra, controle, proteção e demais materiais necessários para as obras civis e estruturas de montagem;\nXXXVIII - posto tarifário: período em horas para aplicação das tarifas de forma diferenciada ao longo do dia, considerando a seguinte divisão:\na) posto tarifário ponta: período composto por 3 horas diárias consecutivas definidas pela distribuidora considerando a curva de carga de seu sistema elétrico, aprovado pela ANEEL para toda a área de concessão ou permissão, não se aplicando aos sábados, domingos, terça-feira de carnaval, sexta-feira da Paixão, Corpus Christi e aos feriados nacionais dos dias 1º de janeiro, 21 de abril, 1º de maio, 7 de setembro, 12 de outubro, 2 de novembro, 15 de novembro, 20 de novembro e 25 de dezembro; (Redação dada pela Resolução Normativa nº 1101/2024)\nb) posto tarifário intermediário: período de duas horas, sendo uma hora imediatamente anterior e outra imediatamente posterior ao horário de ponta, aplicado apenas para o grupo B; e\nc) posto tarifário fora de ponta: período composto pelo conjunto das horas diárias consecutivas e complementares àquelas definidas nos postos ponta e, para o grupo B, intermediário;\nXXXIX - potência ativa: quantidade de energia elétrica solicitada por unidade de tempo, em kW (quilowatts);\nXL - potência disponibilizada: potência que o sistema elétrico da distribuidora deve dispor para atender aos equipamentos elétricos e instalações do consumidor e demais usuários;\nXLI - pré-pagamento: modalidade de faturamento que permite a compra de energia elétrica antes de seu consumo;\nXLII - ramal de entrada: conjunto de condutores e acessórios instalados pelo consumidor entre o ponto de conexão e a medição ou a proteção de suas instalações;\nXLIII - ramal de conexão: conjunto de condutores e acessórios instalados pela distribuidora entre o ponto de derivação de sua rede e o ponto de conexão;\nXLIV - serviços ou atividades essenciais: aqueles cuja interrupção coloque em perigo iminente a sobrevivência, a saúde ou a segurança da população e a seguir indicados:\na) tratamento e abastecimento de água;\nb) produção, transporte e distribuição de energia elétrica, gás e combustíveis;\nc) assistência médica e hospitalar;\nd) unidades hospitalares, institutos médico-legais, centros de hemodiálise e de armazenamento de sangue, centros de produção, armazenamento e distribuição de vacinas e soros antídotos;\ne) funerários;\nf) unidade operacional de transporte coletivo;\ng) captação e tratamento de esgoto e de lixo;\nh) unidade operacional de serviço público de telecomunicações;\ni) guarda, uso e controle de substâncias radioativas, equipamentos e materiais nucleares;\nj) processamento de dados ligados a serviços essenciais;\nk) centro de controle público de tráfego aéreo, marítimo e urbano;\nl) instalações que atendam a sistema rodoferroviário e metroviário;\nm) unidade operacional de segurança pública, tais como polícia e corpo de bombeiros;\nn) câmaras de compensação bancária e unidades do Banco Central do Brasil; e\no) instalações de aduana;\nXLV - serviços auxiliares: sistemas projetados para garantir a continuidade operativa de instalações em regime de operação normal ou de emergência;\nXLV-A - Sistema de Compensação de Energia Elétrica - SCEE: sistema no qual a energia elétrica ativa é injetada p

# 3- Modelo

In [67]:
# ============================================================
# Energy Start — Classificador (1º LLM) usando a API da NVIDIA
# Cole esta célula inteira no Colab e rode.
# A chave fica nos Secrets do Colab (ícone 🔑) com o nome NVIDIA_KEY.
# ============================================================

import json
import re
import time

import pandas as pd
import requests
from google.colab import userdata

URL = "https://integrate.api.nvidia.com/v1/chat/completions"
MODELO = "google/gemma-4-31b-it"
CHAVE = "Bearer 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"

# ------------------------------------------------------------
# 1. Taxonomia: áreas e subáreas do protótipo
# ------------------------------------------------------------
TAXONOMIA = {
    "Solar": {
        "Geração distribuída": "micro e minigeração distribuída, sistema de compensação de energia, "
        "créditos, Fio B, geração compartilhada, autoconsumo remoto, Lei 14.300, reajustes "
        "tarifários que mudam o valor da compensação",
        "Conexão e acesso": "pedido de conexão à rede, prazos da distribuidora, recusa por "
        "inversão de fluxo, requisitos técnicos de conexão",
    },
    "Eólica": {
        "Cortes de geração": "redução de geração determinada pelo operador (curtailment), "
        "regras de ressarcimento",
        "Tarifas e encargos": "tarifas de uso da transmissão, encargos pagos por geradores",
    },
    "Armazenamento": {
        "Autorização de armazenamento": "requisitos e procedimentos para autorizar sistemas de "
        "armazenamento de energia (baterias) autônomos",
        "Conexão e faturamento de armazenamento": "conexão, contratação de uso da rede, "
        "faturamento e baterias instaladas junto a usinas (colocalizadas)",
    },
}

# ------------------------------------------------------------
# 2. Prompt
# ------------------------------------------------------------
def montar_prompt():
    linhas = []
    for area, subs in TAXONOMIA.items():
        linhas.append(f"Área: {area}")
        for sub, desc in subs.items():
            linhas.append(f"  - Subárea: {sub} — {desc}")
    lista = "\n".join(linhas)

    return f"""Você é um analista regulatório do setor elétrico brasileiro.
Sua tarefa é classificar uma norma (resolução, portaria ou despacho) nas áreas e subáreas abaixo.

ÁREAS E SUBÁREAS PERMITIDAS (use somente estas, com os nomes exatamente iguais):
{lista}

REGRAS:
1. Leia o texto inteiro. Uma norma sobre outro assunto pode alterar um artigo que pertence
   a uma subárea (ex.: uma norma sobre tarifa social que muda uma regra de compensação de
   geração distribuída). Nesse caso, classifique na subárea e diga isso na justificativa.
2. Uma norma pode ter mais de uma classificação, ou nenhuma.
3. Use apenas o que está escrito no texto. Não deduza nem use conhecimento próprio.
4. Mencionar uma palavra não basta: a norma precisa criar, alterar ou revogar uma regra
   daquela subárea. Ex.: citar "recursos energéticos distribuídos" de passagem NÃO é
   geração distribuída.
5. Se nada se encaixar, devolva a lista vazia.

FORMATO DA RESPOSTA: apenas um objeto JSON, sem texto antes ou depois, sem ```:
{{"classificacoes": [{{"area": "Solar", "subarea": "Geração distribuída"}}],
  "relevancia": 0,
  "justificativa": "uma frase curta explicando a escolha"}}

"relevancia" vai de 0 a 3:
0 = não afeta nenhuma subárea
1 = afeta pouco ou indiretamente
2 = altera regra de uma subárea
3 = muda regra central de uma subárea (prazo, limite, valor, obrigação)"""

# ------------------------------------------------------------
# 3. Chamada à NVIDIA para um texto
# ------------------------------------------------------------
def _ler_json(resposta):
    limpo = re.sub(r"```(?:json)?", "", resposta)
    return json.loads(limpo[limpo.find("{"): limpo.rfind("}") + 1])


def _validar(dados):
    """Descarta qualquer área/subárea que não esteja na TAXONOMIA."""
    return [(c.get("area"), c.get("subarea")) for c in dados.get("classificacoes", [])
            if c.get("area") in TAXONOMIA and c.get("subarea") in TAXONOMIA[c.get("area")]]


def chamar_nvidia(mensagens):
    headers = {"Authorization": f"{CHAVE}", "Accept": "application/json"}
    payload = {
        "model": MODELO,
        "messages": mensagens,
        "temperature": 0,      # mesma norma -> mesma resposta
        "max_tokens": 1024,    # suficiente para o JSON
        "stream": False,
    }
    r = requests.post(URL, headers=headers, json=payload, timeout=120)
    if r.status_code in (401, 403):
        raise RuntimeError("Chave inválida ou sem permissão. Confira o Secret NVIDIA_KEY.")
    r.raise_for_status()   # outros erros (limite, servidor) sobem para nova tentativa
    return r.json()["choices"][0]["message"]["content"] or ""


def classificar_texto(texto, max_chars=40000):
    mensagens = [
        {"role": "system", "content": montar_prompt()},
        {"role": "user", "content": "NORMA A CLASSIFICAR:\n\n" + texto[:max_chars]},
    ]
    for _ in range(2):  # nova tentativa se o JSON vier quebrado
        try:
            dados = _ler_json(chamar_nvidia(mensagens))
            pares = _validar(dados)
            return {
                "area": sorted({a for a, _ in pares}),
                "subarea": [s for _, s in pares],
                "relevancia": dados.get("relevancia", 0) if pares else 0,
                "justificativa": dados.get("justificativa", ""),
            }
        except (json.JSONDecodeError, ValueError):
            continue
    return {"area": [], "subarea": [], "relevancia": 0, "justificativa": "ERRO: resposta inválida"}

# ------------------------------------------------------------
# 4. Classificar o DataFrame inteiro
# ------------------------------------------------------------
def classificar_df(df, coluna_texto="texto", pausa=7):
    resultados = []
    for i, texto in enumerate(df[coluna_texto].astype(str), start=1):
        for tentativa in range(3):
            try:
                r = classificar_texto(texto)
                break
            except RuntimeError:
                raise                      # chave errada: para na hora
            except Exception as e:
                print(f"  erro na tentativa {tentativa + 1}: {e} — esperando 30s")
                time.sleep(30)
        else:
            r = {"area": [], "subarea": [], "relevancia": 0,
                 "justificativa": "ERRO: limite ou falha da API"}
        print(f"[{i}/{len(df)}] {r['subarea'] or 'nenhuma'} (relevância {r['relevancia']})")
        resultados.append(r)
        time.sleep(pausa)
    return pd.concat([df.reset_index(drop=True), pd.DataFrame(resultados)], axis=1)

# ------------------------------------------------------------
# Uso:
#   teste = classificar_df(novidades.head(1))
#   teste[["titulo", "area", "subarea", "relevancia", "justificativa"]]
# ------------------------------------------------------------

In [68]:
teste = classificar_df(df_normas)
#   teste[["titulo", "area", "subarea", "relevancia", "justificativa"]]

[1/5] nenhuma (relevância 0)
[2/5] nenhuma (relevância 0)
[3/5] nenhuma (relevância 0)
[4/5] nenhuma (relevância 0)
[5/5] ['Conexão e acesso'] (relevância 3)

In [89]:
relevantes = teste[teste["relevancia"] > 0]
relevantes

,arquivo,titulo,data,paginas,caracteres,uso,texto,atos_relacionados,area,subarea,relevancia,justificativa
4,aren2021956_prodist_modulo_3_v8.pdf,"RESOLUÇÃO NORMATIVA ANEEL Nº 956, DE 7 DE DEZE...",NaN,41,1528,novidade,"ANEXO III DA RESOLUÇÃO NORMATIVA ANEEL Nº 956,...",NaN,[Solar],[Conexão e acesso],3,O texto estabelece a estrutura de requisitos t...

In [95]:
relevantes["texto"][4]

'ANEXO III DA RESOLUÇÃO NORMATIVA ANEEL Nº 956, DE 7 DE DEZEMBRO DE 2021 PROCEDIMENTOS DE DISTRIBUIÇÃO DE ENERGIA ELÉTRICA NO SISTEMA ELÉTRICO NACIONAL – PRODIST MÓDULO 3 - CONEXÃO AO SISTEMA DE DISTRIBUIÇÃO DE ENERGIA ELÉTRICA Seção 3.0 Introdução Conteúdo 1. Além desta seção introdutória, este módulo está estruturado da seguinte forma: Seção 3.1 – Requisitos para Conexão de Microgeração e Minigeração Distribuída: estabelece requisitos técnicos para conexão de microgeração e minigeração distribuída ao sistema de distribuição; Seção 3.2 – Requisitos para Conexão de Central Geradora: estabelece requisitos técnicos para conexão de central geradora ao sistema de distribuição; Seção 3.3 – Requisitos de Projeto das Instalações de Conexão: define os requisitos a serem observados para elaboração de projetos de instalações de conexão; Seção 3.4 – Requisitos dos Sistemas de Proteção para demais Usuários: define requisitos gerais de proteção para usuários que não se enquadram nas Seções 3.1 e 3.2; Seção 3.5 – Requisitos de Operação, Manutenção e Segurança da Conexão: estabelece diretrizes para a operação, manutenção e segurança das conexões; e Anexos. Objetivo 2. Estabelecer as instruções detalhadas e os requisitos complementares sobre a regulação da conexão ao sistema de distribuição de energia elétrica disposta nas Regras de Prestação do Serviço Público de Distribuição de Energia Elétrica. Aplicabilidade 3. Os procedimentos definidos neste módulo devem ser observados por:\na) distribuidoras de energia elétrica; e'

In [ ]:
# Vou precisar guardar no banco, o texto, a data, a área e a subárea Para jogar nos alertas.

# 4 ) Testando o Scraping junto com o classificador de relevância:

In [97]:
df = coletar_dia("21-09-2026")

21-09-2026: 75 publicações de ANEEL/MME/CNPE
[1/75] nenhuma (relevância 0)
[2/75] nenhuma (relevância 0)
[3/75] nenhuma (relevância 0)
[4/75] nenhuma (relevância 0)
[5/75] nenhuma (relevância 0)
[6/75] nenhuma (relevância 0)

KeyboardInterrupt:

In [102]:
df_class = classificar_df(df)

# Resolção Autorizativa só passa se tiver o tema citado, caso contrario nao vale a pena
normativos = df["titulo"].str.contains("NORMATIVA|HOMOLOGATÓRIA", case=False, na=False)
temas = "geração distribuída|microgeração|minigeração|compensação de energia|conexão|constrained|corte de geração|eólic|offshore|armazenamento|bateria"
tem_tema = df["texto"].str.contains(temas, case=False, na=False)
para_classificar = df[normativos | tem_tema]

[1/75] nenhuma (relevância 0)
[2/75] nenhuma (relevância 0)
[3/75] nenhuma (relevância 0)
[4/75] nenhuma (relevância 0)
[5/75] nenhuma (relevância 0)

KeyboardInterrupt:

In [104]:
df["texto"][30]

'DESPACHO Nº 3.622, DE 15 DE SETEMBRO DE 2026\nO DIRETOR-GERAL DA AGÊNCIA NACIONAL DE ENERGIA ELÉTRICA - ANEEL, no uso de suas atribuições regimentais, tendo em vista deliberação da Diretoria e o que consta do Processo nº 48500.003422/2026-70, decide:\nconhecer e, no mérito, negar provimento ao Pedido de Impugnação apresentado pela Barra Bonita Óleo e Gás S.A. - Barra Bonita I, cadastrada sob o CNPJ 22.881.417/0001-43, contra a decisão do Conselho de Administração da Câmara de Comercialização de Energia Elétrica - CAd/CCEE, em sua 1.500ª reunião, referente à penalidade por insuficiência de lastro de energia de reserva.\nSANDOVAL DE ARAÚJO FEITOSA NETO\nEste conteúdo não substitui o publicado na versão certificada.\nBorda do rodapé\nLogo da Imprensa'

In [115]:
dados = df[~df["tipo"].isin(["Despacho","Portaria"])]
dados.reset_index(drop=True,inplace=True)

In [121]:
dados

,data,orgao,tipo,titulo,texto,link
0,21/09/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.786, DE 15 DE SET...","RESOLUÇÃO AUTORIZATIVA Nº 16.786, DE 15 DE SET...",https://www.in.gov.br/web/dou/-/resolucao-auto...
1,21/09/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.780, DE 15 DE SET...","RESOLUÇÃO AUTORIZATIVA Nº 16.780, DE 15 DE SET...",https://www.in.gov.br/web/dou/-/resolucao-auto...
2,21/09/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.777, DE 15 DE SET...","RESOLUÇÃO AUTORIZATIVA Nº 16.777, DE 15 DE SET...",https://www.in.gov.br/web/dou/-/resolucao-auto...
3,21/09/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.784, DE 15 DE SET...","RESOLUÇÃO AUTORIZATIVA Nº 16.784, DE 15 DE SET...",https://www.in.gov.br/web/dou/-/resolucao-auto...
4,21/09/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.776, DE 15 DE SET...","RESOLUÇÃO AUTORIZATIVA Nº 16.776, DE 15 DE SET...",https://www.in.gov.br/web/dou/-/resolucao-auto...
5,21/09/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.779, DE 15 DE SET...","RESOLUÇÃO AUTORIZATIVA Nº 16.779, DE 15 DE SET...",https://www.in.gov.br/web/dou/-/resolucao-auto...
6,21/09/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,"RESOLUÇÃO AUTORIZATIVA Nº 16.785, DE 15 DE SET...","RESOLUÇÃO AUTORIZATIVA Nº 16.785, DE 15 DE SET...",https://www.in.gov.br/web/dou/-/resolucao-auto...
7,21/09/2026,Ministério de Minas e Energia/Agência Nacional...,Resolução,RESOLUÇÕES AUTORIZATIVAS DE 15 DE SETEMBRO DE ...,RESOLUÇÕES AUTORIZATIVAS DE 15 DE SETEMBRO DE ...,https://www.in.gov.br/web/dou/-/resolucoes-aut...

In [1]:
dados["texto"]

NameError: name 'dados' is not defined